sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag my_docker_reposetory/swagger_server my_docker_reposetory/swagger_server
- docker push my_docker_reposetory/swagger_server
env:
  global:
  - secure: VUmtnCjSlEREIODsR1DMP9yZYiL7C16Wn3lfVWjkDQtZkF+ZDMVgnuxYavcrkEbjncmizSCGm3Qf+o3GXMGo8LE5tphzaL073YF2MQiXIF2A8glC4cTgVcqgv4Du+SbgIMn/YPxe41mJLNaNSmB6C6k0r3/+K7wX/RORa/ziBunS9PORn8kWuEeS1dur8JCRcvnUW3RhjMtXIi/xZac/lspHVwZTF/mOBZOO7K4VNVHWbUiHwtT6mTJnny5wIiZK29jfXMsQfdO/baqO64xKnWemW66JTk3SzrQmMRxNnitjErBYSFOQDZmDYJY+aqP1Vw7sGEUE5F0N5C12k/vEtIHqHaW3uXPbVdo5iBuoUgUxSedwYFVZkJwcZ21cFkAJdL5hW/+u/OqHZJog5SyqXFzYlWcDXlFRZdGM3R3o2gIP8SqgbzpBK2mfqnEhUG1POXA6OQ/LNuP/xtJJzgciDiIP+vBJfVNmGoK+e8c3cPmhPJTLuG/tJfHrHFZFbLuF+DUk8N4n3Ict3eBjIGfIVCmk95t/2YftQ1htCcXNvkub6bp27REy1ZmknsDSlJ6yVHRFcYVg9PWjT0+Hz3SAKClPEP3eBAr/K6S50WLZLmr523AGy+Z+1HnwdEo4nQtUTtQUcy6vEU1+JU9T93mzn7gYMNo4Oi66A/7zajTOwmY=
  - secure: FPNd6k1FCpuNcjjeR+hLSRiiQa1z1mAAR8sLqSJN7OJmyfJ4wNfrngHFm3iaou64gWYz3ybpRRSm/zFdK0B4L/fs2uyFnBlLPyJGNuhSHKIHlH8c0J9JjHWu/SM8uH+HlpPOlvZ/jYiStnUvZNxpTQOMLQv0ECqsbaNM56MyoEdMv/M+MGOeM4vumloEX7nuacg3DNTPiFdpnK9AJgeaXhGm1Y7ohBnBGemQ7OG21WXorFkchim0lAP+JlV4GfcTMxvPMW05tDU39ZtO4olwSzgsYuXPL3+ofh/kAvYP8OqLlfBK7hjdc/vjPC8l8ToF714CFSyRprZRKSkQLt+6CGIIGuu58NJOUN59XGSMUfFCRntsvTKpu+Q1Xo6yJMNUxG17L3umkDTTdlZqAHZjdAe7vCJka4wk+3wPnPpgOIxbPyMCw+h3gfhTm30+mAucL9H6LEctSab7S9BxXA3AMSeVbDJeyUVxOA1ckyDdPO6oAaaMo/0LoIXwsBUBMiq4cywdf6O6Yl5JjZKX/+2U8KrXhR5ObNMvABlNp7G3n3bcYRJ5Y5wewXHv9eXxFvWUX+mhSVDtU3D14seV7wcGgYOInmx0XcqqMbqN52tlmMVQ9qag/qQdWHPt+l9JudLGAd6oqTz1yPU1aAXrDemvtnwyXIYp+CSMlcrqXpofIAE=
  - secure: GH2UWNpM8YuJOxcB2fRwFvjHBwmFFTRqlO/tD5fqpTdhdxVK9dC0F1Ha42XhyB4Iryu4Wvk0oFvDD86qug4lrDV1FzCaVd3sdUicvCP1C0l1Lwo3L0qhK5jiXYvU8DTvtcrNtSsmHqzRL7gb8itJWnCEP+BOIGeHBu0wvGv9BWqW1zbCyHlZQ4YukPx+DOFxx+q6JceLSCvx08QhiNRJ0e5s0SwChxQK4qwkfcDRBRq3xE7p+jOCnyyFGUTIhuySadU3BRtmNrFpPGxPly/zAZMGTS9FTz8d9ZdX+PnBqDr2tskoppnT92XMwMOF8ZrPrUN8ivKWR99LRTiybBLvX4qhWFybTLjy1QZCPhRzBurbjWLV06/KvPfNhqmpkJH2eZc4FLBDf3XI+cKBqvLJ5xY6kBvsseYJXJQOa8w3qqBoU0fJgFIOZNc1IpXcSLYZLvknrsI0s4d6DjazIV87T3qZnmPTxMDAFI7Lejg8eIOmncVIz1jSfHYMjWc1roP5GxlgRyzWvMHfQerCE856bO9E8tHx5Pp7OVfnG6tcmPkoGIwa6qBrFbmIUSoyVJGEdZXe57zWKBb2logW5WwDj91kYm/Ptp2TVp2VusJXtQR2idinWZ+jAdpv2lDAcI2xRoOSLK1vk0fdRoutvX6XnAyypK25e+UbvVyU+uPErBY=
